using Microsoft.Extensions.Logging;
using PersonalSite.Core.Configuration;
using PersonalSite.Core.Content;
using PersonalSite.Core.Rendering;
using PersonalSite.Core.Services;

namespace PersonalSite.Generator;

public sealed class StaticSiteGenerator(
    IContentDiscoveryService discovery,
    IContentParser parser,
    IMarkdownRenderer markdownRenderer,
    IRouteBuilder routeBuilder,
    INavigationBuilder navigationBuilder,
    ITemplateRenderer templateRenderer,
    IOutputWriter outputWriter,
    ILogger<StaticSiteGenerator> logger) : IStaticSiteGenerator
{
    public async Task GenerateAsync(SiteConfiguration site, string repositoryRoot, CancellationToken cancellationToken = default)
    {
        logger.LogInformation("Generating site '{SiteName}'.", site.SiteName);

        await outputWriter.CleanOutputDirectoryAsync(site, repositoryRoot, cancellationToken);

        var files = await discovery.DiscoverMarkdownFilesAsync(site, repositoryRoot, cancellationToken);
        var pages = new List<ContentPage>();

        foreach (var file in files)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var page = await parser.ParseAsync(file, cancellationToken);
            page.HtmlContent = markdownRenderer.RenderToHtml(page.MarkdownContent);
            page.Url = routeBuilder.BuildUrl(page);
            page.OutputPath = routeBuilder.BuildOutputPath(site, repositoryRoot, page);
            pages.Add(page);
        }

        ValidateRoutes(pages);

        var orderedPages = pages
            .OrderBy(page => page.Metadata.Order)
            .ThenBy(page => page.Metadata.Title, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        foreach (var page in orderedPages)
        {
            var context = new RenderContext
            {
                Site = site,
                Page = page,
                Pages = orderedPages,
                Navigation = navigationBuilder.BuildNavigation(page, orderedPages)
            };

            var html = await templateRenderer.RenderPageAsync(context, repositoryRoot, cancellationToken);
            await outputWriter.WritePageAsync(site, repositoryRoot, page, html, cancellationToken);
        }

        await outputWriter.CopyAssetsAsync(site, repositoryRoot, cancellationToken);

        logger.LogInformation("Generated {PageCount} pages into {OutputDirectory}.", orderedPages.Length, site.OutputDirectory);
    }

    private static void ValidateRoutes(IEnumerable<ContentPage> pages)
    {
        var duplicateRoute = pages
            .GroupBy(page => page.Url, StringComparer.OrdinalIgnoreCase)
            .FirstOrDefault(group => group.Count() > 1);

        if (duplicateRoute is not null)
        {
            var sources = string.Join(", ", duplicateRoute.Select(page => page.SourcePath));
            throw new InvalidOperationException($"Duplicate route '{duplicateRoute.Key}' was generated by: {sources}");
        }
    }
}
